spring:
  application:
    name: techpick-server
  output:
    ansi:
      enabled: always
  sql:
    init:
      mode: never # schema.sql 실행시 always 키고 실행하시면 됩니다. option: never, always

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  datasource:
    url: ${DOCKER_MYSQL_URL}
    username: ${DOCKER_MYSQL_USERNAME}
    password: ${DOCKER_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

#logging: # /* Transaction Logging */
#  level:
#    org.springframework.orm.jpa: DEBUG

---

spring:
  config:
    activate:
      on-profile: local
  jpa:
    properties:
      hibernate:
        format_sql: false
        show_sql: true
    hibernate:
      ddl-auto: create
core:
  base-url: http://localhost:8080

---

spring:
  config:
    activate:
      on-profile: dev
  jpa:
    properties:
      hibernate:
        format_sql: false
        show_sql: false
    hibernate:
      ddl-auto: update
core:
  base-url: https://v2.minlife.me

---

spring:
  config:
    activate:
      on-profile: prod
  jpa:
    properties:
      hibernate:
        format_sql: false
        show_sql: false
    hibernate:
      ddl-auto: none
core:
  base-url: https://api.techpick.org

---