# 참고 설정
# https://github.com/Kernel360/E2E2-TALKKA/blob/develop/server/src/main/resources/application.yaml
# https://github.com/kimminkyeu/E2E2-LOOK-US/blob/develop/backend/src/main/resources/application.yml

spring:
  application:
    name: techpick-core
  output:
    ansi:
      enabled: always
  sql:
    init:
      mode: never # schema.sql 실행시 always 키고 실행하시면 됩니다. option: never, always

  jpa:
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update # 이 부분 설정 주의 필요

  datasource:
    url: ${DOCKER_MYSQL_URL}
    username: ${DOCKER_MYSQL_USERNAME}
    password: ${DOCKER_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jwt:
    secret:
      ${JWT_SECRET}
    issuer:
      ${JWT_ISSUER}

  # OAuth2 관련 설정
  config:
    import: classpath:oauth2-config.yaml

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
  api-docs:
    path: /api-docs
  show-actuator: true
  # swagger 가 패키지를 포함하여 관리하게 함 -> 같은 클래스내의 inner class 또한 구분 가능
  # ex) TagApiResponse.Create TagApiResponse.Move 를 구분할 수 있음
  use-fqn: true

api:
  base-url: ${TECHPICK_BASE_URL}