spring:
  application:
    name: techpick-server
  output:
    ansi:
      enabled: always
  sql:
    init:
      mode: never # schema.sql 실행시 always 키고 실행하시면 됩니다. option: never, always

  jpa:
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update # 이 부분 설정 주의 필요
    open-in-view: false
  datasource:
    url: ${DOCKER_MYSQL_URL}
    username: ${DOCKER_MYSQL_USERNAME}
    password: ${DOCKER_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

#logging: # /* Transaction Logging */
#  level:
#    org.springframework.orm.jpa: DEBUG

---

spring:
  config:
    activate:
      on-profile: local
core:
  base-url: http://localhost:8080

---

spring:
  config:
    activate:
      on-profile: dev
core:
  base-url: https://api.minlife.me

---

spring:
  config:
    activate:
      on-profile: prod
core:
  base-url: https://api.techpick.org

---