# 참고 설정
# https://github.com/Kernel360/E2E2-TALKKA/blob/develop/docker-compose.yaml
# https://github.com/Kernel360/E2E2-LOOK-US/blob/develop/backend/docker-compose.yaml

# Local 테스트 전용 Compose 입니다.
# 실행시 앱 이미지를 로컬에 빌드합니다. (배포 버전에서는 빌드하지 않고, 도커 허브에서 가져옴)

# name: techpick-dev

networks:
  techpick-network:
    driver: bridge

services:
  techpick-mysql:
    image: mysql:8.0
    container_name: techpick-mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DOCKER_MYSQL_PASSWORD}
      - MYSQL_DATABASE=${DOCKER_MYSQL_DATABASE}
      - TZ=Asia/Seoul
    volumes:
      - ./data/develop/mysql-data:/var/lib/mysql
      - ./data/develop/mysql-files:/var/lib/mysql-files/develop
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    networks:
      - techpick-network

#  techpick-mysql-test:
#    image: mysql:8.0
#    container_name: techpick-mysql-test
#    ports:
#      - "3307:3306"
#    env_file:
#      - .env
#    environment:
#      - MYSQL_ROOT_PASSWORD=${DOCKER_MYSQL_TEST_PASSWORD}
#      - MYSQL_DATABASE=${DOCKER_MYSQL_TEST_DATABASE}
#      - TZ=Asia/Seoul
#    volumes:
#      - ./data/test/mysql-data:/var/lib/mysql
#      - ./data/test/mysql-files:/var/lib/mysql-files/test
#    command:
#      - --character-set-server=utf8mb4
#      - --collation-server=utf8mb4_unicode_ci
#      - --lower_case_table_names=1
#    networks:
#      - techpick-network
#  로컬 테스트 용 ( 아래 설정은 실제 서버에 올라간 Compose 와 다름 )
#  techpick-server:
#    build:
#      dockerfile: Dockerfile
#    container_name: techpick-server
#    ports:
#      - "8080:8080"
#    env_file:
#        - .env
#    depends_on:
#      - techpick-mysql
#    networks:
#      - techpick-network
