# Local 테스트 전용 Compose 입니다.
# 실행시 앱 이미지를 로컬에 빌드합니다. (배포 버전에서는 빌드하지 않고, 도커 허브에서 가져옴)

# name: techpick-dev

networks:
  techpick-network:
    driver: bridge

services:
  techpick-mysql:
    # **********************************
    #          MYSQL RDB
    # **********************************
    image: mysql:8.0
    container_name: techpick-mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DOCKER_MYSQL_PASSWORD}
      - MYSQL_DATABASE=${DOCKER_MYSQL_DATABASE}
      - TZ=Asia/Seoul
    volumes:
      - ./data/mysql-data:/var/lib/mysql
      - ./data/mysql-files:/var/lib/mysql-files/develop
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    networks:
      - techpick-network

  techpick-mongo:
    # **********************************
    #          MONGO NoSQL DB
    # **********************************
    image: mongo
    container_name: techpick-mongo
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DOCKER_MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DOCKER_MONGO_PASSWORD}
    volumes:
      - ./data/mongo:/data/db
    command: [ "--bind_ip", "0.0.0.0" ]
    networks:
      - techpick-network

  techpick-api:
    # **********************************
    #          TECHPICK API SERVER
    # **********************************
    build:
      context: ./techpick-api
      dockerfile: Dockerfile
    container_name: techpick-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - LOCAL_MYSQL_URL=${DOCKER_MYSQL_URL}
      - DOCKER_MYSQL_USERNAME=${DOCKER_MYSQL_USERNAME}
      - DOCKER_MYSQL_PASSWORD=${DOCKER_MYSQL_PASSWORD}
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=local
    networks:
      - techpick-network
    depends_on:
      - techpick-mysql

  techpick-batch:
    # **********************************
    #       TECHPICK BATCH SERVER
    # **********************************
    build:
      context: ./techpick-batch
      dockerfile: Dockerfile
    container_name: techpick-batch
    env_file:
      - .env
    environment:
      - LOCAL_MYSQL_URL=${DOCKER_MYSQL_URL}
      - DOCKER_MYSQL_USERNAME=${DOCKER_MYSQL_USERNAME}
      - DOCKER_MYSQL_PASSWORD=${DOCKER_MYSQL_PASSWORD}
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=local
    networks:
      - techpick-network
    depends_on:
      - techpick-mysql

  techpick-rabbitmq:
    # **********************************
    #       TECHPICK MESSAGE QUEUE
    # **********************************
    image: rabbitmq:3-management
    container_name: techpick-rabbitmq
    hostname: techpick
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - "15672:15672" # 관리 UI 포트
      - "5672:5672" # AMQP 포트