# Local 테스트 전용 Compose 입니다.
# 실행시 앱 이미지를 로컬에 빌드합니다. (배포 버전에서는 빌드하지 않고, 도커 허브에서 가져옴)

# name: techpick-dev

networks:
  techpick-network:
    driver: bridge

services:
  techpick-mysql:
    image: mysql:8.0
    container_name: techpick-mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DOCKER_MYSQL_PASSWORD}
      - MYSQL_DATABASE=${DOCKER_MYSQL_DATABASE}
      - TZ=Asia/Seoul
    volumes:
      - ./data/develop/mysql-data:/var/lib/mysql
      - ./data/develop/mysql-files:/var/lib/mysql-files/develop
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    networks:
      - techpick-network

  techpick-api:
    build:
      context: ./techpick-api
      dockerfile: Dockerfile
    container_name: techpick-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DOCKER_MYSQL_URL=jdbc:mysql://techpick-mysql/TECHPICK_DB?createDatabaseIfNotExist=true
      - DOCKER_MYSQL_USERNAME=root
      - DOCKER_MYSQL_PASSWORD=1234
      - TZ=Asia/Seoul
    networks:
      - techpick-network
    depends_on:
      - techpick-mysql

  techpick-batch:
    build:
      context: ./techpick-batch
      dockerfile: Dockerfile
    container_name: techpick-batch
    ports:
      - "8081:8080"
    env_file:
      - .env
    environment:
      - DOCKER_MYSQL_URL=jdbc:mysql://techpick-mysql/TECHPICK_DB?createDatabaseIfNotExist=true
      - DOCKER_MYSQL_USERNAME=root
      - DOCKER_MYSQL_PASSWORD=1234
      - TZ=Asia/Seoul
    networks:
      - techpick-network
    depends_on:
      - techpick-mysql

