logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
            # MongoTemplate: DEBUG # MongoDB Query Logging

# swagger setting
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
  api-docs:
    path: /api-docs
  show-actuator: true
  # swagger가 패키지를 포함 관리, 같은 클래스내의 inner class 또한 구분 가능. Ex) TagApiResponse.Create TagApiResponse.Move 를 구분할 수 있음
  use-fqn: true

spring:
  profiles:
    include:
      - common
  application:
    name: baguni.${PROFILE_MODE}.server.ranking
  output:
    ansi:
      enabled: always
  # MongoDB를 위해 JPA 자동 설정을 제외.
  # https://stackoverflow.com/questions/51221777/failed-to-configure-a-datasource-url-attribute-is-not-specified-and-no-embedd
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: mongodb://${DOCKER_MONGO_USERNAME}:${DOCKER_MONGO_PASSWORD}@${DOCKER_LOCAL_MONGO_URL}/${DOCKER_MONGO_DATABASE}?authSource=${DOCKER_MONGO_AUTH}
      database: ${DOCKER_MONGO_DATABASE}
      username: ${DOCKER_MONGO_USERNAME}
      password: ${DOCKER_MONGO_PASSWORD}
server:
  port: 8082
---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      uri: mongodb://${DOCKER_MONGO_USERNAME}:${DOCKER_MONGO_PASSWORD}@${DOCKER_DEV_MONGO_URL}/${DOCKER_MONGO_DATABASE}?authSource=${DOCKER_MONGO_AUTH}
      database: ${DOCKER_MONGO_DATABASE}
      username: ${DOCKER_MONGO_USERNAME}
      password: ${DOCKER_MONGO_PASSWORD}
server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      uri: mongodb://${DOCKER_MONGO_USERNAME}:${DOCKER_MONGO_PASSWORD}@${DOCKER_PROD_MONGO_URL}/${DOCKER_MONGO_DATABASE}?authSource=${DOCKER_MONGO_AUTH}
      database: ${DOCKER_MONGO_DATABASE}
      username: ${DOCKER_MONGO_USERNAME}
      password: ${DOCKER_MONGO_PASSWORD}
springdoc: # 운영 환경에서 스웨거 접근 못하도록 막는 설정
  api-docs:
    enabled: false # false로 변경하면, swagger api-docs(정적 json 파일) 접근 불가
  swagger-ui:
    enabled: false # false로 변경하면, swagger 접근 불가
server:
  port: 8080
---