# -----------------------------
#       COMMON SETTINGS
# -----------------------------
spring:
  output:
    ansi:
      enabled: always
  sql:
    init:
      mode: never # schema.sql 실행시 always 키고 실행하시면 됩니다. option: never, always
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        format_sql: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DOCKER_MYSQL_USERNAME}
    password: ${DOCKER_MYSQL_PASSWORD}
  flyway:
    user: ${DOCKER_MYSQL_USERNAME}
    password: ${DOCKER_MYSQL_PASSWORD}
    schemas: ${DOCKER_MYSQL_DATABASE}
logging:
  level:
    # basic log level for all messages
    org.hibernate: info
    # SQL statements and parameters
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    # Statistics and slow queries
    org.hibernate.stat: debug
    org.hibernate.SQL_SLOW: info
    # 2nd Level Cache
    org.hibernate.cache: debug
---
# -----------------------------
#       LOCAL SETTINGS
# -----------------------------
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${DOCKER_LOCAL_MYSQL_URL}
  flyway:
    url: ${DOCKER_LOCAL_MYSQL_URL}
    baseline-on-migrate: true
    enabled: true
decorator:
  datasource:
    p6spy:
      enable-logging: true
---
# -----------------------------
#     DEVELOPMENT SETTINGS
# -----------------------------
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${DOCKER_DEV_MYSQL_URL}
  flyway:
    url: ${DOCKER_DEV_MYSQL_URL}
    baseline-on-migrate: true
    enabled: true
decorator:
  datasource:
    p6spy:
      enable-logging: true
---
# -----------------------------
#     DEVELOPMENT SETTINGS
# -----------------------------
spring:
  config:
    activate:
      on-profile: staging
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: ${DOCKER_STAGING_MYSQL_URL}
  flyway:
    url: ${DOCKER_STAGING_MYSQL_URL}
    baseline-on-migrate: true
    enabled: true
decorator:
  datasource:
    p6spy: # 스테이징 서버에서는 p6spy 로깅을 사용하지 않음
      enable-logging: false
---
# -----------------------------
#     PRODUCTION SETTINGS
# -----------------------------
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: ${DOCKER_PROD_MYSQL_URL}
  flyway:
    url: ${DOCKER_PROD_MYSQL_URL}
    baseline-on-migrate: true
    enabled: true
decorator:
  datasource:
    p6spy: # 운영 서버에서는 p6spy 로깅을 사용하지 않음
      enable-logging: false