logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
#              MongoTemplate: DEBUG # MongoDB Query Logging
spring:
  profiles:
    include:
      - core
  application:
    name: 'techpick.service.ranking'
  output:
    ansi:
      enabled: always
  sql:
    init:
      mode: never # schema.sql 실행시 always 키고 실행하시면 됩니다. option: never, always
---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: mongodb://${DOCKER_MONGO_USERNAME}:${DOCKER_MONGO_PASSWORD}@${LOCAL_MONGO_URL}/${DOCKER_MONGO_DATABASE}?authSource=${DOCKER_MONGO_AUTH}
      database: ${DOCKER_MONGO_DATABASE}
      username: ${DOCKER_MONGO_USERNAME}
      password: ${DOCKER_MONGO_PASSWORD}
server:
  port: 8082
---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      uri: mongodb://${DOCKER_MONGO_USERNAME}:${DOCKER_MONGO_PASSWORD}@${DOCKER_MONGO_URL}/${DOCKER_MONGO_DATABASE}?authSource=${DOCKER_MONGO_AUTH}
      database: ${DOCKER_MONGO_DATABASE}
      username: ${DOCKER_MONGO_USERNAME}
      password: ${DOCKER_MONGO_PASSWORD}
server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      uri: mongodb://${DOCKER_MONGO_USERNAME}:${DOCKER_MONGO_PASSWORD}@${DOCKER_MONGO_URL}/${DOCKER_MONGO_DATABASE}?authSource=${DOCKER_MONGO_AUTH}
      database: ${DOCKER_MONGO_DATABASE}
      username: ${DOCKER_MONGO_USERNAME}
      password: ${DOCKER_MONGO_PASSWORD}
server:
  port: 8080
---