# 로컬에서 techpick-api와 동시에 켜야 할 경우 아래 주석을 해제하세요
server:
  port: 8082

spring:
  profiles:
    include:
      - core
  application:
    name: techpick-ranking
  output:
    ansi:
      enabled: always
  sql:
    init:
      mode: never # schema.sql 실행시 always 키고 실행하시면 됩니다. option: never, always
---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: mongodb://${DOCKER_MONGO_USERNAME}:${DOCKER_MONGO_PASSWORD}@${LOCAL_MONGO_URL}/${DOCKER_MONGO_DATABASE}?authSource=${DOCKER_MONGO_AUTH}
      database: ${DOCKER_MONGO_DATABASE}
      username: ${DOCKER_MONGO_USERNAME}
      password: ${DOCKER_MONGO_PASSWORD}

  rabbitmq:
    host: ${LOCAL_RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      uri: mongodb://${DOCKER_MONGO_USERNAME}:${DOCKER_MONGO_PASSWORD}@${DOCKER_MONGO_URL}/${DOCKER_MONGO_DATABASE}?authSource=${DOCKER_MONGO_AUTH}
      database: ${DOCKER_MONGO_DATABASE}
      username: ${DOCKER_MONGO_USERNAME}
      password: ${DOCKER_MONGO_PASSWORD}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
---

