---
spring:
  profiles:
    include:
      - infra
      - common
---
# -----------------------------
#       LOCAL SETTINGS
# -----------------------------
spring:
  config:
    activate:
      on-profile: local
  application:
    name: baguni.local.server.batch
server:
  port: 8081 # 로컬에선 api 서버가 8080 포트를 사용하기 때문
---
# -----------------------------
#       DEVELOPMENT SETTINGS
# -----------------------------
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: baguni.dev.server.batch
server:
  port: 8080
---
# -----------------------------
#       STAGING SETTINGS
# -----------------------------
spring:
  config:
    activate:
      on-profile: staging
  application:
    name: baguni.staging.server.batch
server:
  port: 8080
---
# -----------------------------
#       PRODUCTION SETTINGS
# -----------------------------
spring:
  config:
    activate:
      on-profile: prod
  application:
    name: baguni.prod.server.batch
server:
  port: 8080