---
spring:
  profiles:
    include:
      - domain
      - common
  application:
    name: baguni.${PROFILE_MODE}.server.batch
---
# -----------------------------
#       LOCAL SETTINGS
# -----------------------------
spring:
  config:
    activate:
      on-profile: local
server:
  port: 8081 # 로컬에선 api 서버가 8080 포트를 사용하기 때문
---
# -----------------------------
#       DEVELOPMENT SETTINGS
# -----------------------------
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8080
---
# -----------------------------
#       STAGING SETTINGS
# -----------------------------
spring:
  config:
    activate:
      on-profile: staging
server:
  port: 8080
---
# -----------------------------
#       PRODUCTION SETTINGS
# -----------------------------
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 8080