---
spring:
  profiles:
    include:
      - domain
      - common
  application:
    name: baguni.${PROFILE_MODE}.server.batch
---
spring:
  config:
    activate:
      on-profile: local
server:
  port: 8081
slack-config:
  webhook-url: "" # 로컬은 알림 없음
---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8080
slack-config:
  webhook-url: ${SLACK_DEV_WEBHOOK_URL}
---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 8080
slack-config:
  webhook-url: ${SLACK_PROD_WEBHOOK_URL}